### ISSUE TITLE
Getting and Error with Unprompted and Dynamic Prompting

### ISSUE THREAD

**Issue by JohnWJarrett** [ThereforeGames/unprompted#16]
Getting this every prompt when I'm using the Dynamic_Prompting extension:

Error running process: J:\SD\ASD\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "J:\SD\ASD\modules\scripts.py", line 307, in process
      script.process(p, *script_args)
  File "J:\SD\ASD\extensions\unprompted\scripts\unprompted.py", line 54, in process
   Unprompted.shortcode_user_vars["prompt"] = Unprompted.process_string(original_prompt)
  File "J:\SD\ASD\extensions\unprompted\lib\shared.py", line 68, in process_string
    string = self.shortcode_parser.parse(string).replace(self.Config.syntax.n_temp," ")
AttributeError: 'list' object has no attribute 'replace'

Is there a way to tell Unprompted to just chill when it's not needed?

**Comment by JohnWJarrett** [comment]
Eh, I'm just going to remove it. the error and just unprompted in general means it takes forever for a large batch to start as it tries to find (This is what I am guessing after all) any matches in the X amount of prompts that DP is making.

**Comment by ThereforeGames** [comment]
Hi @JohnWJarrett,

Thank you for your findings!

Unfortunately, A1111's documentation is a bit sparse when it comes to getting extensions to play well with each other. l need to run some tests to learn how the WebUI prioritizes execution.

If you don't mind me asking, what is the purpose of running Unprompted and Dynamic Prompting simultaneously?

**Comment by Harvester62** [comment]
I can confirm that Dynamic Prompts and Unprompted are incompatible, in the sense that if Unprompted is installed AND activated in the Extensions tab, Dynamic Prompts doesn't work properly and the functions named "Magic Prompt" and "I'm feeling luky" won't work any more. 
This was discovered after deep testing with the Dynamic Prompts developer. Unless the developer of Unprompted will discover what is interfering with Dynamic Prompts, the only solution is to do not activate both extensions at the same time, but only one or the other. We can still keep both installed. 

Dynamic Prompts provide a couple of very nice tools like the "Magic Prompts" (https://github.com/adieyal/sd-dynamic-prompts#magic-prompt) and "I'm feeling lucky" (https://github.com/adieyal/sd-dynamic-prompts#im-feeling-lucky) which automatically add further terms to an initially given prompt using the Lexica.art API.

**Comment by ThereforeGames** [comment]
Hi @Harvester62,

Thanks for your findings - I'm going to install a copy of Dynamic Prompts and see if I can figure out why Unprompted isn't playing well with it. It sounds like "Magic Prompts" and "I'm feeling lucky" are good reasons to have both plugins installed.

**Comment by Harvester62** [comment]
Hi @ThereforeGames, this would be great, thank you. I think that both extensions have good reasons to be kept installed and used. Hope you find a solution and if you need anything from my side, let me know.

**Comment by ThereforeGames** [comment]
Hi guys,

Quick update. Here's what I've found after installing the Dynamic Prompts extension alongside Unprompted:

- A1111 WebUI can run txt2img and img2img without crashing, so I may have already fixed the original issue.
- It seems that Unprompted overrides Dynamic Prompts' execution. I still need to dig into A1111's source code to understand why this is happening, but if I had to guess, the UI might process extensions in alphabetical order. The effect that Dynamic Prompts has on the all-important `p` object does not seem to get passed on to Unprompted. **EDIT:** After more tests I can confirm that Dynamic runs first but Unprompted does not receive its changes to the prompt object.
- I cannot find anything in the A1111 docs about inter-extension compatibility: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

Either I am overlooking something or we are up against a limitation of the extension system. Worst case scenario, Unprompted can probably call Dynamic Prompts' `process()` function manually, but I would prefer to find a less hacky solution. If anyone can point me in the right direction I'd appreciate it!

**Comment by Harvester62** [comment]
Hi, I let the developer of Dynamic Prompts know about your research for a solution to this incompatibility issue, hoping that you might find together the cause and the solution to this problem. Here is the link to the bug report I reopened there: https://github.com/adieyal/sd-dynamic-prompts/issues/91#issue-1474142461

**Comment by adieyal** [comment]
I wonder whether the easiest solution is to simply provide a checkbox that disables Unprompted. Dynamic Prompts has an opt out checkbox for this reason.  Is there a common use case for using both extensions at the same time?

![Screenshot from 2022-12-03 22-34-06](https://user-images.githubusercontent.com/420786/205461030-12beb4d9-69bd-49bd-a758-e52f5ec024cc.png)

**Comment by Harvester62** [comment]
I think this is a good idea, at least until a solution will be found, if it will exist. 
One suggestion, make a  "Unprompted Enabled" checkbox disabled by default, or make it as "Unprompted Disabled" and checked by default, so that Dynamic Prompts works fine by default and when you want to use Unprompted it's simply a matter of enabling/disabling this option. One of the two options should work. Yes, let's try this way. 
I hope that anyway you or the developer of Dynamic Prompts will be able to find out why this is happening and if it's fixable in the future. Thank you for looking into this matter.

**Comment by ThereforeGames** [comment]
Hi folks,

I may have addressed the underlying issue in v2.0.2 - it looks like Unprompted *does* receive changes to `all_prompts` so I have updated the script to utilize this variable instead.

Feel free to give the new version a try and let me know if it seems more compatible with Dynamic Prompts. Thanks!

**Comment by adieyal** [comment]
That's great news.

**Comment by Harvester62** [comment]
I will give a try for sure, thank you!

**Comment by Harvester62** [comment]
Unfortunately, I still get an error at startup with Unprompted:

Error loading script: unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 18, in <module>
    from lib.shared import Unprompted
ModuleNotFoundError: No module named 'lib.shared'

Therefore Unprompted is not being loaded and I cannot test it.

**Comment by kingsushi001** [comment]
> Unfortunately, I still get an error at startup with Unprompted:
> 
> Error loading script: unprompted.py Traceback (most recent call last): File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts module = script_loading.load_module(scriptfile.path) File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module exec(compiled, module.**dict**) File "C:\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 18, in from lib.shared import Unprompted ModuleNotFoundError: No module named 'lib.shared'
> 
> Therefore Unprompted is not being loaded and I cannot test it.

Same here. Have tried everything. It just doesn't work

**Comment by ThereforeGames** [comment]
Closing as I believe the underlying issue was resolved (the `lib` folder was renamed to `lib_unprompted` months ago.)
